version: "v3"

x-app-image: &app-image ${APP_IMAGE:-""}

x-mariadb-vars: &mariadb-vars
  MARIADB_DATABASE: railsbase_container
  MARIADB_USER: railsbase_container
  MARIADB_PASSWORD: thecakeisalie
  MARIADB_ROOT_PASSWORD: thecakeisalie

x-common-vars: &common-vars
  PORT: 5000
  REDIS_URL: "redis://redis:6379/1"
  MYSQL_HOST: mariadb
  MYSQL_DATABASE: railsbase_container
  MYSQL_USERNAME: railsbase_container
  MYSQL_PASSWORD: thecakeisalie
  WAIT_FOR_TARGETS: |-
    mariadb:3306

networks:
  default:
    name: local

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment: *mariadb-vars
    ports:
      - 3306:3306
    volumes:
      - ./docker/data/mariadb:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    image: *app-image
    profiles:
      - app
    depends_on:
      - mariadb
      - redis
    ports:
      - 5000:5000
    command: bundle exec puma -C config/puma.rb
    environment: *common-vars
